sonar.projectKey=mobile-wallet-verifier-certificate-signing-requests
sonar.projectName=mobile-wallet-verifier-certificate-signing-requests
sonar.organization=govuk-one-login

sonar.sources=src,scripts/lib
sonar.tests=scripts/unit,tests
sonar.exclusions=**/*.test.ts,**/*.steps.ts,**/*.feature

sonar.cpd.exclusions=**/template.yaml,**/package-lock.json

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.language=ts
sonar.sourceEncoding=UTF-8