sonar.projectKey=mobile-wallet-verifier-certificate-signing-requests
sonar.projectName=mobile-wallet-verifier-certificate-signing-requests
sonar.organization=govuk-one-login

sonar.sources=src,scripts/lib
sonar.tests=src,scripts/unit,tests
sonar.test.inclusions=**/*.test.ts,tests/**/*,src/**/tests/utils/**,src/utils/test/**
sonar.exclusions=**/*.test.ts,tests/**/*,src/**/tests/utils/**,src/utils/test/**,**/*.steps.ts,**/*.feature

sonar.cpd.exclusions=**/template.yaml,**/package-lock.json

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.language=ts
sonar.sourceEncoding=UTF-8

sonar.issue.ignore.multicriteria=s9382SequentialRecords,s2699CucumberSteps
sonar.issue.ignore.multicriteria.s9382SequentialRecords.ruleKey=typescript:S9382
sonar.issue.ignore.multicriteria.s9382SequentialRecords.resourceKey=src/csr-validator/handler.ts
sonar.issue.ignore.multicriteria.s2699CucumberSteps.ruleKey=typescript:S2699
sonar.issue.ignore.multicriteria.s2699CucumberSteps.resourceKey=tests/infraTests/step-definitions/*.steps.ts
